export const  CommitsActionTypes =  {
        FETCH_COMMITS_START:'FETCH_COMMITS_START',
        FETCH_COMMITS_SUCCESS:'FETCH_COMMITS_SUCCESS',
        FETCH_COMMITS_FAILURE:'FETCH_COMMITS_FAILURE',
        CLEAR_DATA: 'CLEAR_DATA'
}