export const  UserActionTypes =  {
        CHECK_USERNAME_START:'CHECK_USERNAME_START',
        CHECK_USERNAME_SUCCESS:'CHECK_USERNAME_SUCCESS',
        CHECK_USERNAME_FAILURE:'CHECK_USERNAME_FAILURE',
        LOGIN_START:'LOGIN_START',
        LOGIN_SUCCESS:'LOGIN_SUCCESS',
        LOGIN_FAILURE:'LOGIN_FAILURE',
        LOGOUT:'LOGOUT',
        GET_AUTH: 'GET_AUTH'
}